### ISSUE TITLE
Explorer doesn't show anything

### ISSUE THREAD

**Issue by Jiniix806** [mikeoverbay/PKGexplorer#1]
Im not exactly sure how to use this, but from what I saw, you just set path to PKG files to WoT's res_mods/1.15.0.0 folder (current version of WoT) and Export to location to the same one. But it doesn't show anything. Any help?

**Comment by amelkikh** [comment]
I guess this is happened because internal format of pkg changed and author did not update parser over 1 year. It's a pity but u shouldn't be relying on any updates

**Comment by Jiniix806** [comment]
Forgot to mention: Im stupid, didn't watch your tutorial video.

**Comment by mikeoverbay** [comment]
> I guess this is happened because internal format of pkg changed and author did not update parser over 1 year. It's a pity but u shouldn't be relying on any updates

I have to update Pak explorer to work with the current game. Sometimes, WG changes things that make the app useless.
I'm not sure how I'm suppose to write it so it can fix it's self to work with updates to how the PKG files are named or the intern data.
